In [1]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [2]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [4]:
# code here

team_stats = df.groupby('Team')[['Total Attempts', 'On Target']].sum()
team_stats['percentage'] = (team_stats['On Target'] / team_stats['Total Attempts']) * 100

team_stats['percentage'] = team_stats['percentage'].round(2)
result = team_stats['percentage'].sort_values(ascending=False).to_dict()
print(result)

{'Costa Rica': 54.55, 'Cameroon': 51.85, 'Ecuador': 48.15, 'Argentina': 46.15, 'Brazil': 45.56, 'England': 45.0, 'Portugal': 40.32, 'Ghana': 40.0, 'Netherlands': 39.02, 'Korea Republic': 36.73, 'Australia': 36.0, 'Mexico': 34.88, 'France': 34.65, 'Germany': 34.33, 'Croatia': 33.73, 'Spain': 32.69, 'Belgium': 32.35, 'Serbia': 32.26, 'Iran': 31.43, 'Uruguay': 31.25, 'United States': 31.11, 'Saudi Arabia': 31.03, 'Senegal': 30.77, 'Denmark': 30.56, 'Switzerland': 30.56, 'Japan': 30.23, 'Wales': 29.17, 'Qatar': 28.57, 'Morocco': 28.33, 'Tunisia': 26.67, 'Poland': 25.0, 'Canada': 17.65}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [5]:
# code here

matches = df['Team'].value_counts()

rankings = matches.rank(ascending=False, method='first')

result = pd.DataFrame({
    'Matches_Played': matches, 
    'Rank': rankings
})

print(result)

                Matches_Played  Rank
Team
France                       7   1.0
Argentina                    7   2.0
Croatia                      7   3.0
Morocco                      7   4.0
Brazil                       5   5.0
Portugal                     5   6.0
England                      5   7.0
Netherlands                  5   8.0
Spain                        4   9.0
Japan                        4  10.0
Switzerland                  4  11.0
Korea Republic               4  12.0
Australia                    4  13.0
Poland                       4  14.0
Senegal                      4  15.0
United States                4  16.0
Mexico                       3  17.0
Saudi Arabia                 3  18.0
Denmark                      3  19.0
Tunisia                      3  20.0
Iran                         3  21.0
Ecuador                      3  22.0
Qatar                        3  23.0
Wales                        3  24.0
Canada                       3  25.0
Belgium                      3  26.0
Costa Rica                   3  27.0
Germany                      3  28.0
Uruguay                      3  29.0
Cameroon                     3  30.0
Ghana                        3  31.0
Serbia                       3  32.0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [6]:
# code here

df.info()

df.describe()

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)

df.drop_duplicates(inplace=True)

df.drop(columns=['Sl. No', 'Match No.', 'Red Cards', 'Pts'], inplace=True)

print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB
Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
dtype: int64
      Team      Against Group  Goal  Possession (%)  Inside Penalty Area  \
0    Qatar      Ecuador     A     0              40                    0
1  Ecuador        Qatar     A     2              46                    2
2  England         Iran     B     6              69                    6
3     Iran      England     B     2              20                    2
4  Senegal  Netherlands     A     0              39                    0

   Outside Penalty Area  Assists  Total Attempts  On Target  Off Target  \
0                     0        0               5          0           5
1                     0        1               5          5           2
2                     0        6              13          7           3
3                     0        1               8          3           4
4                     0        0              15          4           7

   Target in Penalty  Target from Outside  Left Channel  Left Inside Channel  \
0                  2                    3            15                    0
1                  4                    1             8                    7
2                 10                    3            11                    5
3                  6                    2             3                    0
4                  8                    7            12                    4

   Central Channel  Right Inside Channel  Right Channel  Receptions MD  \
0                3                     1              9             45
1                6                     4              6             55
2                2                     3             11             72
3                3                     1              1             34
4                2                     4             13            101

   Receptions D  Attempted Line Breaks  Completed Line Breaks  \
0             5                    159                    100
1            10                    159                    103
2            15                    133                     94
3             1                     56                     19
4            12                    143                     86

   Attempted Defensive Line Breaks  Completed Defensive Line Breaks  \
0                                6                                4
1                                6                                4
2                                8                                6
3                                1                                1
4                                6                                6

   Yellow Cards  Fouls Against  Offsides  Passes  Passes Completed  Crosses  \
0             4             15         3     453               387       10
1             2             15         4     484               419       26
2             0              9         2     810               733       29
3             2             14         2     232               156       11
4             2             13         2     391               326       22

   Crosses Completed  Corners  Free Kicks  Penalties Scored
0                  5        1          19                 0
1                 10        3          17                 1
2                  9        8          16                 0
3                  3        0          10                 1
4                  8        6          14                 0

### `Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [7]:
# code here

df['Rank'] = df['Team'].rank(method='first')
df['Rank'] = df['Rank'].astype(np.int16)
df.set_index('Rank', inplace=True)
df.sort_index(inplace=True)

print(df.head())

           Team       Against Group  Goal  Possession (%)  \
Rank
1     Argentina  Saudi Arabia     C     1              51
2     Argentina        Mexico     C     2              50
3     Argentina        Poland     C     2              67
4     Argentina     Australia     C     2              53
5     Argentina   Netherlands     C     2              44

      Inside Penalty Area  Outside Penalty Area  Assists  Total Attempts  \
Rank
1                       1                     0        0              14
2                       1                     1        2               5
3                       1                     1        2              25
4                       2                     0        1              14
5                       2                     0        1              15

      On Target  Off Target  Target in Penalty  Target from Outside  \
Rank
1             6           6                 10                    4
2             2           3                  2                    3
3            13           8                 10                   15
4             5           7                 11                    3
5             6           8                  5                   10

      Left Channel  Left Inside Channel  Central Channel  \
Rank
1               12                    4                5
2               10                    6                2
3               25                    8                7
4               15                    6               11
5                7                    7               13

      Right Inside Channel  Right Channel  Receptions MD  Receptions D  \
Rank
1                        8             18             91            27
2                        4             12             89             2
3                       10             26            150            36
4                        2             17            127             8
5                        6             17            104             7

      Attempted Line Breaks  Completed Line Breaks  \
Rank
1                       195                    127
2                       150                    100
3                       141                    126
4                       181                    135
5                       203                    122

      Attempted Defensive Line Breaks  Completed Defensive Line Breaks  \
Rank
1                                  10                                8
2                                  10                                5
3                                  20                               16
4                                  16                                8
5                                  24                                8

      Yellow Cards  Fouls Against  Offsides  Passes  Passes Completed  \
Rank
1                0              7        10     593               525
2                1             15         2     533               464
3                1             11         0     862               814
4                0              8         4     711               635
5                8             18         2     603               511

      Crosses  Crosses Completed  Corners  Free Kicks  Penalties Scored
Rank
1          36                 15        9          21                 1
2          14                  2        4          23                 0
3          22                  5        9           5                 0
4           6                  1        1          15                 0
5          16                  4        8          30                 5

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [8]:
# code here

df1 = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv")
df1.dropna(subset=['Age'], inplace=True)

df2 = pd.read_csv(" https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv")
df2['Age'].fillna(20, inplace=True)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

### `Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [9]:
# code here

ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"
ipl = pd.read_csv(ipl_matches)

team_map = {
'Delhi Daredevils':'Delhi Capitals',
'Kings XI Punjab':'Punjab Kings',
'Rising Pune Supergiants':'Rising Pune Supergiant'
}

cols = ['Team1','Team2','WinningTeam','TossWinner']
ipl[cols] = ipl[cols].replace(team_map)

ipl = ipl[ipl['WinningTeam'].notna()]

matches_played = pd.concat([ipl['Team1'],ipl['Team2']]).value_counts()
wins = ipl['WinningTeam'].value_counts()
home_wins = ipl[ipl['WinningTeam']==ipl['Team1']]['Team1'].value_counts()
away_wins = ipl[ipl['WinningTeam']==ipl['Team2']]['Team2'].value_counts()

df = pd.DataFrame({
'Team Name':matches_played.index,
'Matches Played':matches_played
})

df['Wins'] = df['Team Name'].map(wins).fillna(0)
df['Home Wins'] = df['Team Name'].map(home_wins).fillna(0)
df['Away Wins'] = df['Team Name'].map(away_wins).fillna(0)

df['Win %'] = df['Wins']/df['Matches Played']*100
df['Home Win %'] = df['Home Wins']/df['Matches Played']*100
df['Away Win %'] = df['Away Wins']/df['Matches Played']*100

df.sort_values('Win %',ascending=False)

,Team Name,Matches Played,Wins,Home Wins,Away Wins,Win %,Home Win %,Away Win %
Gujarat Titans,Gujarat Titans,16,12,4,8,75.000000,25.000000,50.000000
Lucknow Super Giants,Lucknow Super Giants,15,9,7,2,60.000000,46.666667,13.333333
Chennai Super Kings,Chennai Super Kings,208,121,65,56,58.173077,31.250000,26.923077
Mumbai Indians,Mumbai Indians,231,131,65,66,56.709957,28.138528,28.571429
Kolkata Knight Riders,Kolkata Knight Riders,223,114,56,58,51.121076,25.112108,26.008969
Rajasthan Royals,Rajasthan Royals,190,96,49,47,50.526316,25.789474,24.736842
Rising Pune Supergiant,Rising Pune Supergiant,30,15,7,8,50.000000,23.333333,26.666667
Sunrisers Hyderabad,Sunrisers Hyderabad,152,75,36,39,49.342105,23.684211,25.657895
Royal Challengers Bangalore,Royal Challengers Bangalore,223,109,61,48,48.878924,27.354260,21.524664
Delhi Capitals,Delhi Capitals,222,103,53,50,46.396396,23.873874,22.522523
Punjab Kings,Punjab Kings,218,101,50,51,46.330275,22.935780,23.394495
Gujarat Lions,Gujarat Lions,30,13,5,8,43.333333,16.666667,26.666667
Kochi Tuskers Kerala,Kochi Tuskers Kerala,14,6,3,3,42.857143,21.428571,21.428571
Deccan Chargers,Deccan Chargers,75,29,13,16,38.666667,17.333333,21.333333
Pune Warriors,Pune Warriors,45,12,6,6,26.666667,13.333333,13.333333

### `Q-7:` Venues with most "no result" matches.

In [10]:
# code here

ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"
ipl = pd.read_csv(ipl_matches)
no_result = ipl[ipl['WinningTeam'].isna()]

venue_counts = no_result['Venue'].value_counts()

print(venue_counts)

Venue
M Chinnaswamy Stadium    2
M.Chinnaswamy Stadium    1
Feroz Shah Kotla         1
Name: count, dtype: int64

### `Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [11]:
# code here

ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"
ipl = pd.read_csv(ipl_matches)

finals = ipl[ipl['MatchNumber'] == 'Final']
players = pd.concat([finals['Team1Players'], finals['Team2Players']])
players = players.str.split(',').explode().str.strip()

top_player = players.value_counts().idxmax()
print(top_player)

'MS Dhoni'

### `Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [12]:
# code here

def point_table(season):
    df = ipl[ipl['Season'] == season].copy()

    # All team participations
    teams_played = pd.concat([df['Team1'], df['Team2']])
    matches_played = teams_played.value_counts()

    # Wins
    wins = df['WinningTeam'].value_counts()

    # No result matches (WinningTeam is NaN)
    no_result_matches = df[df['WinningTeam'].isna()]
    no_result = pd.concat([no_result_matches['Team1'], 
                           no_result_matches['Team2']]).value_counts()

    # Build table
    table = pd.DataFrame({
        'MatchesPlayed': matches_played,
        'MatchesWon': matches_played.index.map(wins).fillna(0).astype(int),
        'NoResult': matches_played.index.map(no_result).fillna(0).astype(int)
    })

    table['Points'] = table['MatchesWon']*2 + table['NoResult']*1

    table.index.name = 'TeamName'

    # Sorting: points descending, team name ascending
    table = table.sort_values(by=['Points','TeamName'], 
                              ascending=[False, True])

    return table

In [13]:
point_table('2022').head(2)

                  MatchesPlayed  MatchesWon  NoResult  Points
TeamName
Gujarat Titans               16          12         0      24
Rajasthan Royals             17          10         0      20

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [14]:
# code here

def point_table_extended(season):

    table = point_table(season).copy()

    season_df = ipl[ipl['Season'] == season]

    # --- Final ---
    final = season_df[season_df['MatchNumber'] == 'Final'].iloc[0]
    winner = final['WinningTeam']
    runner = final['Team1'] if final['Team2'] == winner else final['Team2']

    # --- Qualifier 2 ---
    q2 = season_df[season_df['MatchNumber'] == 'Qualifier 2'].iloc[0]
    loser_q2 = q2['Team1'] if q2['WinningTeam'] == q2['Team2'] else q2['Team2']

    # --- Eliminator ---
    elim = season_df[season_df['MatchNumber'] == 'Eliminator'].iloc[0]
    loser_elim = elim['Team1'] if elim['WinningTeam'] == elim['Team2'] else elim['Team2']

    # create column
    table['SeasonPosition'] = table['Points'].rank(method='first', ascending=False)

    # set playoff positions
    table.at[winner, 'SeasonPosition'] = 'Winner'
    table.at[runner, 'SeasonPosition'] = 'Runner'
    table.at[loser_q2, 'SeasonPosition'] = 3
    table.at[loser_elim, 'SeasonPosition'] = 4

    return table

In [15]:
point_table_extended('2022')

/tmp/ipykernel_97015/590348700.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Winner' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table.at[winner, 'SeasonPosition'] = 'Winner'

,MatchesPlayed,MatchesWon,NoResult,Points,SeasonPosition
TeamName,,,,,
Gujarat Titans,16,12,0,24,Winner
Rajasthan Royals,17,10,0,20,Runner
Lucknow Super Giants,15,9,0,18,4
Royal Challengers Bangalore,16,9,0,18,3
Delhi Capitals,14,7,0,14,5.0
Punjab Kings,14,7,0,14,6.0
Kolkata Knight Riders,14,6,0,12,7.0
Sunrisers Hyderabad,14,6,0,12,8.0
Chennai Super Kings,14,4,0,8,9.0
Mumbai Indians,14,4,0,8,10.0